builds:
  -
    id: mackerel-checks-exporter-linux
    main: main.go
    binary: mackerel-checks-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
nfpms:
  -
    id: mackerel-checks-exporter-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - mackerel-checks-exporter-linux
    homepage: https://github.com/pama86/mackerel-checks-exporter
    maintainer: Kazuhiko Yamashita <www.kazu.com@gmail.com>
    description: Mackerel migration exporter
    license: Apache License 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    contents:
      - src: ./package-assets/mackerel-checks-exporter.service
        dst: /etc/systemd/system/mackerel-checks-exporter.service
        type: config
      - src: ./package-assets/mackerel-checks-exporter
        dst: /etc/default/mackerel-checks-exporter
        type: config
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - 'pyama/mackerel-check-plugin-exporter{{ .Version }}-amd64'
      - 'pyama/mackerel-check-plugin-exporter:latest-amd64'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  -
    goos: linux
    goarch: arm64
    image_templates:
      - 'pyama/mackerel-check-plugin-exporter{{ .Version }}-arm64'
      - 'pyama/mackerel-check-plugin-exporter:latest-arm64'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
- name_template: 'pyama/mackerel-check-plugin-exporter{{ .Version }}'
  image_templates:
  - 'pyama/mackerel-check-plugin-exporter{{ .Version }}-arm64'
  - 'pyama/mackerel-check-plugin-exporter{{ .Version }}-amd64'
- name_template: 'pyama/mackerel-check-plugin-exporter:latest'
  image_templates:
  - 'pyama/mackerel-check-plugin-exporter:latest-arm64'
  - 'pyama/mackerel-check-plugin-exporter:latest-amd64'
