builds:
  -
    id: mackerel-checks-exporter-linux
    main: main.go
    ldflags:
      - -s -w
    binary: mackerel-checks-exporter
    env:
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
  -
    id: mackerel-checks-exporter-darwin
    main: main.go
    ldflags:
      - -s -w
    binary: mackerel-checks-exporter
    env:
      - GO111MODULE=on
    goos:
      - darwin
    goarch:
      - amd64
nfpms:
  -
    id: mackerel-checks-exporter-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - mackerel-checks-exporter-linux
    homepage: https://github.com/pama86/mackerel-checks-exporter
    maintainer: Kazuhiko Yamashita <www.kazu.com@gmail.com>
    description: Mackerel migration exporter
    license: Apache License 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
